name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Test
        env:
          MY_DOCKER_HOST: 172.17.0.1
        run: npm t
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: stderr
          path: stderr
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
